#!/bin/bash -e

/home/communityprofiles/.virtualenvs/2017Profiles/bin/supervisorctl \
-c /home/communityprofiles/checkouts/2017-Profiles/profiles/supervisord/test-profiles.conf \
restart all > /tmp/logrotate-profiles-2017.log;

