app:
    secret:                     2246 Tudor
    host:                       ie.216software.com
    scheme:                     http
    launch_debugger_on_error:   False
    webapp_port:                6659
    pidfile:                    /tmp/profiles-webapp.pid
    num_webapp_workers:         4

postgresql:
    database:   ieint_dev
    user:       matt
    host:       null
    port:       null
    password:   null

smtp:
    host: &smtphost  localhost

logging:

    default: &defaultlogging

        # This is the catch-all.
        # root:
        #     level: DEBUG
        #     handlers: [console, tmpfile]

        loggers:
            profiles: &profileslogging
                propagate: False
                level: DEBUG
                handlers: [console, tmpfile]

            werkzeug: *profileslogging

            horsemeat: *profileslogging

        disable_existing_loggers: false

        version: 1

        handlers:

            console:
                class: logging.StreamHandler
                level: DEBUG
                formatter: consolefmt

            tmpfile:
                class: logging.FileHandler
                filename: /tmp/profiles.log
                mode: a
                level: DEBUG
                formatter: consolefmt

            email:
                level: CRITICAL
                formatter: consolefmt
                class: logging.handlers.SMTPHandler
                mailhost: *smtphost

                fromaddr: profiles@profiles

                toaddrs:
                    - matt@tplus1.com
                    # - robert.heinen@gmail.com

                subject: production error

        formatters:
            consolefmt:
                format: '%(asctime)-22s [%(process)d] %(name)-30s %(lineno)-5d %(levelname)-8s %(message)s'

    script: *defaultlogging

profiles:

    weekly_manifest_email_recipients:
        -   matt@216software.com


# vim: set filetype=yaml :
