
app:

    secret:                     2246 Tudor
    host: &host                 profiles.216software.com
    scheme:                     http
    launch_debugger_on_error:   False
    webapp_port:                6660
    pidfile:                    /tmp/prod-profiles-webapp.pid
    num_webapp_workers:         1

postgresql:
    database:   &dbname profiles_prod
    user:       &dbuser profiles
    host:       &dbhost localhost
    port:       &dbport 5432
    password:   &dbpass pr0f1l3s

smtp:
    host: &smtphost  localhost

logging:

    default:

        # This is the catch-all.
        # root:
        #     level: DEBUG
        #     handlers: [console, textfile]

        loggers:
            pyprofiles: &defaultlogging
                propagate: False
                level: DEBUG
                # handlers: [console, pg, textfile]
                handlers: [console, textfile, email]

            werkzeug: *defaultlogging

            horsemeat: *defaultlogging

        disable_existing_loggers: false

        version: 1

        handlers:

            console:
                class: logging.StreamHandler
                level: DEBUG
                formatter: colorfmt

            pg:
                class:          logtopg.PGHandler
                level:          DEBUG
                log_table_name: profileslogs
                database:       *dbname
                host:           *dbhost
                user:           *dbuser
                password:       *dbpass

            textfile:
                class: logging.FileHandler
                filename: /var/log/profiles/pyprofiles.log
                mode: a
                level: DEBUG
                formatter: consolefmt

            email:
                level: CRITICAL
                formatter: consolefmt
                class: logging.handlers.SMTPHandler
                mailhost: *smtphost

                fromaddr: profiles@profiles.216software.com

                toaddrs:
                    - info@216software.com

                subject: production error

        formatters:
            consolefmt:
                format: '%(asctime)-22s [%(process)d] %(name)-30s %(lineno)-5d %(levelname)-8s %(message)s'

            colorfmt:
                (): "colorlog.ColoredFormatter"

                # format: "%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s"

                format: "%(log_color)s%(asctime)-22s [%(process)d] %(name)-30s %(lineno)-5d %(levelname)-8s %(message)s"

    script:

        # This is the catch-all.
        # root:
        #     level: DEBUG
        #     handlers: [console, textfile]

        loggers:
            pyprofiles: &scriptlogging
                propagate: False
                level: DEBUG
                # handlers: [console, pg, textfile]
                handlers: [console, textfile]

            werkzeug: *scriptlogging

            horsemeat: *scriptlogging

        disable_existing_loggers: false

        version: 1

        handlers:

            console:
                class: logging.StreamHandler
                level: WARNING
                formatter: colorfmt

            pg:
                class:          logtopg.PGHandler
                level:          DEBUG
                log_table_name: profileslogs
                database:       *dbname
                host:           *dbhost
                user:           *dbuser
                password:       *dbpass

            textfile:
                class: logging.FileHandler
                filename: /var/log/profiles/pyprofiles.log
                mode: a
                level: DEBUG
                formatter: consolefmt

            email:
                level: CRITICAL
                formatter: consolefmt
                class: logging.handlers.SMTPHandler
                mailhost: *smtphost

                fromaddr: pyprofiles@*host

                toaddrs:
                    - matt@216software.com
                    # - robert.heinen@gmail.com

                subject: production error

        formatters:
            consolefmt:
                format: '%(asctime)-22s [%(process)d] %(name)-30s %(lineno)-5d %(levelname)-8s %(message)s'


            colorfmt:
                (): "colorlog.ColoredFormatter"

                # format: "%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s"

                format: "%(log_color)s%(asctime)-22s [%(process)d] %(name)-30s %(lineno)-5d %(levelname)-8s %(message)s"

google:
    google_maps_API_key:    AIzaSyBigZQyl666oFxkCvg6WM9vBW9-1F8-Hho


# vim: set filetype=yaml :
