#! /bin/bash -e

if (( $# != 1 ))
then

    echo "usage: $0 yaml_file"
    exit 99;

else

    DBNAME=`profiles-config $1 database_name`
    DBUSER=`profiles-config $1 database_user`

    # Maybe create a user.
    DBUSER_EXISTS=`sudo -u postgres psql -t -c "select exists(select usename from pg_user where usename = '$DBUSER');" | sed 's/ *//'`

    if [ "$DBUSER_EXISTS" != "t" ]

    then
        sudo -u postgres createuser --superuser $DBUSER;
    fi;

    sudo -u postgres dropdb --if-exists $DBNAME
    sudo -u postgres createdb --owner $DBUSER $DBNAME
    sudo -u postgres createlang plpythonu $DBNAME
    sudo -u postgres psql --quiet --no-psqlrc -d $DBNAME -c 'create extension "hstore";'
    sudo -u postgres psql --quiet --no-psqlrc -d $DBNAME -c 'create extension "uuid-ossp";'
    sudo -u postgres psql --quiet --no-psqlrc -d $DBNAME -c 'create extension "pgcrypto";'
    sudo -u postgres psql --quiet --no-psqlrc -d $DBNAME -c 'create extension "citext";'
    sudo -u postgres psql --quiet --no-psqlrc -d $DBNAME -c "create extension btree_gist;"
    sudo -u postgres psql --quiet --no-psqlrc -d $DBNAME -c "create extension postgis;"
    sudo -u postgres psql --quiet --no-psqlrc -d $DBNAME -c "create extension postgis_topology;"

    sudo -u postgres psql -d $DBNAME -c "alter database $DBNAME set timezone to 'US/Eastern';"

    echo "Now run profiles-upgrade-database $1"

fi
